# Generated by Django 5.0.2 on 2024-03-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciencechapter_title', models.CharField(max_length=50)),
                ('sciencechapter_description', models.TextField()),
            ],
        ),
    ]
