# Generated by Django 5.0.2 on 2024-03-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mathchapter_title', models.CharField(max_length=50)),
                ('mathchapter_description', models.TextField()),
            ],
        ),
    ]
